# Generated by Django 2.0.3 on 2018-04-24 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CategoryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Категория работ')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
            },
        ),
        migrations.CreateModel(
            name='ClientCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='Пробег')),
                ('year_of_manufacture', models.DateField(verbose_name='Год выпуска')),
                ('numberplate', models.CharField(max_length=9, verbose_name='Номерной знак')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Cars', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Автомобиль клиента',
                'verbose_name_plural': 'Автомобили клиентов',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='DescriptionCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_app.Cars', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Описание автомобиля',
                'verbose_name_plural': 'Описание автомобиля',
            },
        ),
        migrations.CreateModel(
            name='DescriptionCategoryForCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Описание')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Cars', verbose_name='Автомобиль')),
                ('category_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.CategoryJob', verbose_name='Категория работ')),
            ],
            options={
                'verbose_name': 'Описание работы',
                'verbose_name_plural': 'Описание работ',
            },
        ),
        migrations.CreateModel(
            name='DescriptionCategoryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_app.CategoryJob', verbose_name='Категория работ')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
            },
        ),
        migrations.CreateModel(
            name='DetailOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, verbose_name='Статус заказа')),
                ('registration_date', models.DateTimeField(verbose_name='Дата оформления')),
                ('execution_date', models.DateTimeField(verbose_name='Дата исполнения')),
                ('number', models.IntegerField(default=1, verbose_name='Количество')),
                ('total', models.FloatField(default=1, verbose_name='Итого')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Необходимые работы',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('passport', models.CharField(max_length=10, verbose_name='Серия и номер паспорта')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Работа')),
                ('hour_norm', models.FloatField(max_length=10, verbose_name='Нормо-час')),
                ('price_per_hour', models.FloatField(max_length=10, verbose_name='Цена за час')),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.Cars', verbose_name='Автомобиль')),
                ('category_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.CategoryJob', verbose_name='Категория работ')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, verbose_name='Статус заказа')),
                ('registration_date', models.DateTimeField(verbose_name='Дата оформления')),
                ('execution_date', models.DateTimeField(verbose_name='Дата исполнения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Clients', verbose_name='Клиент')),
                ('client_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.ClientCars', verbose_name='Автомобиль')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='job',
            field=models.ManyToManyField(blank=True, to='service_app.Jobs'),
        ),
        migrations.AddField(
            model_name='detailorders',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Employees', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='detailorders',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Jobs', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='detailorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='clientcars',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Clients'),
        ),
        migrations.AddField(
            model_name='categoryjob',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Service', verbose_name='Услуга'),
        ),
    ]
