# Generated by Django 2.0.3 on 2018-04-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailorders',
            name='total',
        ),
    ]
