# Generated by Django 2.0.3 on 2018-05-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_remove_detailorders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Cars', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.Employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='execution_date',
            field=models.DateTimeField(null=True, verbose_name='Дата исполнения'),
        ),
    ]
