# Generated by Django 2.0.3 on 2018-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_auto_20180502_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorders',
            name='execution_date',
            field=models.DateTimeField(null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
